services:
  db:
    image: postgres:18-alpine
    container_name: plantcare_db
    environment:
      POSTGRES_USER: plantcare
      POSTGRES_PASSWORD: ${DB_PASSWORD:-plantcare}
      POSTGRES_DB: plantcare
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
